## **Basic concept**

Basic concept about probability

In [1]:
import numpy as np

# Tao ra mang cac gia tri co kha nang xay ra
possibilities = np.array([0,1,2,3,4,5,6,7])

# So luong mau can sinh ra
size = 5

# Sinh ra cac mau ngau nhien
samples = np.random.choice(possibilities, size)

print(samples)

[3 1 5 4 3]


Uniform distribution (Phân phối đồng nhất)

In [8]:
# Thiet lap mot phan phoi dong nhat
low = 2 # Gioi han duoi
high = 5 # Gioi han tren
size = 5 # so luong mau

# Sinh ra cac mau ngau nhien
samples = np.random.uniform(low, high, size)

print(samples)

[2.06678022 4.44173262 4.12581722 3.07365941 3.70184615]


## **Coin toss problem**

In [30]:
import random

# randint(0,1) will return 0 or 1
value = random.randint(0,1)
print(value)

1


In [11]:
import numpy as np

# Total flips
total_flips = 10000

# number of heads appearing
total_heads = 0

# number of tails appearing
total_tails = 0

#
for i in range(total_flips):
  value = random.randint(0,1)
  if value == 0:
    total_heads += 1
  else:
    total_tails += 1

# Head probability
head_probability = total_heads / total_flips

# Tail probability
tail_probability = total_tails / total_flips

print("Total flips: ", total_flips)
print("Total heads: ", total_heads)
print("Total tails: ", total_tails)
print(f"Head probability: {head_probability}")
print(f"Tail probability: {tail_probability}")

Total flips:  10000
Total heads:  4963
Total tails:  5037
Head probability: 0.4963
Tail probability: 0.5037


## **The problem of estimating the number π**

In [14]:
import random
import math

n_loop = 10

for i in range(n_loop):
  rand_value = random.random() #Return random number between 0.0 and 1.0:
  print(rand_value)

0.9393815421719742
0.06646180811184166
0.7042836098983765
0.8245668697749668
0.5529968351849787
0.8654768662653554
0.979181180208132
0.7758951449252521
0.4498288767218599
0.6626467824088955


In [15]:
# Total point in square
Ns = 1000000

# Total point in circle
Nc = 0

# square edge
s = 2
# radius r = 1
# Point in square have coordinates (x,y) value [-1,1]

for i in range(Ns):
  x = random.random()*2 - 1
  y = random.random()*2 - 1
  # distance to center O(0,0)
  distance = math.sqrt(x**2 + y**2)
  if distance <= 1:
    Nc += 1

pi = (s**2) * Nc / Ns
print(f"pi = {pi}")


pi = 3.141044


## **Gaussian**

6.1 Set up Gaussian function with input is a number

In [ ]:
import math

In [19]:

def gaussian_with_input_number(x, mean = 0, standard_devitation = 1):
  result = 1/(standard_devitation * math.sqrt(2*math.pi))*math.exp((-(x -mean)**2)/(2*standard_devitation**2))
  return round(result,2)


6.2 Set up Gaussian function with input is a list

In [22]:
def gaussian_with_input_list(list, mean = 0, standard_devitation = 1):
  result = []
  for value in list:
    result.append(gaussian_with_input_number(value, mean, standard_devitation))
  return result

6.3 Set up Gaussian function with input is a numpy array

In [25]:
def gaussian_with_input_numpy_array(np_arr, mean = 0, standard_devitation = 1):
  result = []
  for value in np_arr:
    result.append(gaussian_with_input_number(value, mean, standard_devitation))
  return np.round(np.array(result),2)

Testing

In [20]:
# q1
x = 0.5
mean = 1
standard_devitation = 2
gaussian_with_input_number(x, mean, standard_devitation)

0.19

In [23]:
#q2
list = [-3, -0.4, 2]
mean = 0
standard_devitation = 2
gaussian_with_input_list(list, mean, standard_devitation)

[0.06, 0.2, 0.12]

In [26]:
#q3
np_arr = np.array([-0.1, 0.01, -3])
mean = 0
standard_devitation = 3
gaussian_with_input_numpy_array(np_arr, mean, standard_devitation)

array([0.13, 0.13, 0.08])

## **Classical Probability**

In [34]:
import random

# start num
start_test = 1
#stop num
stop_test = 5
# will return num in range start stop
values_test = random.randint(start_test,stop_test)
print(values_test)


4


In [38]:
seed_test = 0
print(random.seed(seed_test))

None


In [54]:
def generate_dice_rolls(n, seed = 0):
  """ Generate a list of dice rolls for an n- sided die , with a fixed seed for reproducibility . """
  # start num
  start = 1
  #stop num
  stop = 6
  random.seed(seed)
  return [random.randint(start,stop)  for _ in range(n)]

In [55]:
def count_occurrences(dice_rolls, number):
  """ Count the occurrences of a specific number in the list of dice rolls ."""
  count = 0
  for roll in dice_rolls:
    if roll == number:
      count += 1
  return count


In [57]:
def calculate_probability(dice_rolls, number):
  """ Calculate the probability of a specific number based on the dice rolls ."""
  return count_occurrences(dice_rolls, number) / len(dice_rolls)


In [58]:
#q5-6
number_of_interest = 6
number_of_dice_rolls = 1000
seed = 0
dice_rolls = generate_dice_rolls(number_of_dice_rolls, seed)
print(f"dice_rolls: {dice_rolls}")
occurrences = count_occurrences(dice_rolls, number_of_interest)
print(f"The occurrences of {number_of_interest} is: {occurrences}")
probability = calculate_probability(dice_rolls, number_of_interest)
print(f"The probability of {number_of_interest} is: {probability}")

dice_rolls: [4, 4, 1, 3, 5, 4, 4, 3, 4, 3, 5, 2, 5, 2, 3, 2, 1, 5, 3, 5, 6, 5, 2, 3, 1, 6, 1, 6, 3, 4, 5, 1, 3, 4, 3, 5, 6, 2, 5, 4, 4, 5, 3, 1, 5, 1, 1, 6, 4, 6, 6, 6, 1, 5, 4, 3, 2, 6, 3, 6, 1, 2, 5, 2, 2, 2, 5, 4, 1, 1, 3, 5, 4, 1, 3, 5, 3, 6, 1, 5, 3, 5, 2, 5, 5, 5, 3, 4, 1, 5, 4, 3, 5, 2, 3, 2, 2, 2, 1, 5, 6, 3, 4, 1, 1, 6, 2, 2, 1, 1, 6, 5, 6, 4, 6, 5, 3, 5, 2, 2, 6, 5, 4, 5, 3, 4, 4, 6, 6, 6, 3, 1, 3, 5, 1, 4, 5, 6, 3, 2, 2, 1, 6, 3, 1, 6, 2, 3, 2, 3, 4, 1, 1, 2, 6, 2, 1, 5, 6, 5, 5, 6, 1, 1, 1, 6, 2, 5, 5, 1, 4, 1, 3, 1, 1, 5, 1, 2, 2, 6, 1, 4, 2, 6, 1, 6, 1, 5, 4, 5, 1, 3, 1, 2, 1, 6, 3, 3, 4, 2, 1, 5, 4, 1, 5, 1, 6, 4, 2, 3, 3, 6, 4, 5, 2, 6, 6, 2, 1, 6, 2, 2, 3, 5, 3, 1, 5, 4, 6, 2, 1, 4, 6, 4, 5, 5, 3, 6, 3, 4, 6, 3, 2, 5, 6, 1, 4, 6, 1, 3, 6, 1, 5, 3, 2, 2, 4, 3, 5, 3, 6, 3, 5, 6, 5, 2, 6, 3, 4, 6, 4, 6, 1, 1, 5, 2, 6, 3, 2, 2, 2, 6, 4, 4, 6, 6, 5, 4, 1, 4, 6, 5, 4, 6, 6, 1, 2, 4, 1, 3, 6, 2, 4, 5, 4, 5, 5, 1, 1, 4, 3, 3, 4, 1, 4, 2, 5, 6, 1, 6, 2, 1, 4, 6, 4, 3, 1, 2, 1, 

## **Numpy**

In [68]:
#
import numpy as np

list_data = [2,3,6,7,9,2]
arr = np.array(list_data)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.nbytes)
print(arr.itemsize)

np.zeros(5)

shape = (2,3)
np.ones(shape)

num = 5
print(np.ones(num))
shape = (2,3)
print(np.ones(shape))
print(np.full(shape, 2))
#
start = 2
stop = 10
step = 2
print(np.arange(start, stop, step))
#
start = 2
stop = 10
num = 5
print(np.linspace(start, stop, num))
#
np.eye(3)
# seed

[2 3 6 7 9 2]
int64
(6,)
1
6
48
8
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]
[2 4 6 8]
[ 2.  4.  6.  8. 10.]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
rand_array = np.random.rand(2, 3)
print(rand_array)


[[0.60596387 0.58328902 0.65207089]
 [0.82568269 0.21725984 0.81787938]]


In [70]:
randint_array = np.random.randint(1, 10,(3, 3))
print(randint_array)

[[3 5 7]
 [3 1 3]
 [9 4 5]]


In [ ]:
#indexing
#slicing


In [72]:
#hstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
print(arr1)
print("+")
print(arr2)
print("=")
print(arr3)

[1 2 3]
+
[4 5 6]
=
[1 2 3 4 5 6]


In [73]:
#vstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.vstack((arr1, arr2))
print(arr1)
print("+")
print(arr2)
print("=")
print(arr3)

[1 2 3]
+
[4 5 6]
=
[[1 2 3]
 [4 5 6]]


In [74]:
#concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print(arr1)
print("+")
print(arr2)
print("=")
print(arr3)
#

[1 2 3]
+
[4 5 6]
=
[1 2 3 4 5 6]


In [76]:
#concatenate
arr1 = np.array([[1, 2, 3],[7, 1, 2]])
arr2 = np.array([[2, 0, 8],[4, 5, 6]])
arr3 = np.concatenate((arr1, arr2),axis=1)
print(arr1)
print("+")
print(arr2)
print("=")
print(arr3)

[[1 2 3]
 [7 1 2]]
+
[[2 0 8]
 [4 5 6]]
=
[[1 2 3 2 0 8]
 [7 1 2 4 5 6]]


In [77]:
#concatenate
arr1 = np.array([[1, 2, 3],[7, 1, 2]])
arr2 = np.array([[2, 0, 8],[4, 5, 6]])
arr3 = np.concatenate((arr1, arr2),axis=0)
print(arr1)
print("+")
print(arr2)
print("=")
print(arr3)

[[1 2 3]
 [7 1 2]]
+
[[2 0 8]
 [4 5 6]]
=
[[1 2 3]
 [7 1 2]
 [2 0 8]
 [4 5 6]]


In [78]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr.reshape(2, 3)
print(arr)
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [79]:
#where
arr = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.where(arr > 3)
print(arr)
print(arr2)

[1 2 3 4 5 6]
(array([3, 4, 5]),)


In [80]:
#array min max
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.min(arr))
print(np.max(arr))

1
6


In [85]:
#min in array by row
arr = np.array([[1, 2, 3],[7, 1, 2]])
print(arr)
print(np.min(arr, axis=1))
#argmax: find index of max value of array
print(np.argmax(arr, axis=1))

#max in array by column
print(np.max(arr, axis=0))

[[1 2 3]
 [7 1 2]]
[1 1]
[2 0]
[7 2 3]


In [88]:
#array sort
arr = np.array([1, 9, 3, 0, 5, 3])
print(np.sort(arr))

# sort array having shape (2,3)
arr = np.array([[1, 2, 3],[7, 1, 2]])
print(np.sort(arr, axis=0))
# axis=1 for row

[0 1 3 3 5 9]
[[1 1 2]
 [7 2 3]]


In [91]:
#inner product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.inner(arr1, arr2)
print(arr1)
print("*")
print(arr2)
print("=")
print(arr3)

[1 2 3]
*
[4 5 6]
=
32


In [92]:
#dot 2 arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.dot(arr1, arr2)
print(arr1)
print("*")
print(arr2)
print("=")
print(arr3)

[1 2 3]
*
[4 5 6]
=
32


In [98]:
# Matrix-matrix multiplication
arr1 = np.array([[1, 2, 3],[7, 1, 2]])
arr2 = np.array([[2, 8],[4, 6],[1, 3]])
print(f"{arr1}")
print(f"arr1 shape:{arr1.shape}")

print("*")
print(f"{arr2}")
print(f"arr2 shape:{arr2.shape}")
print("=")
print(np.matmul(arr1, arr2))

#transpose
print(f"arr2 transpose:")
print(np.transpose(arr2))

[[1 2 3]
 [7 1 2]]
arr1 shape:(2, 3)
*
[[2 8]
 [4 6]
 [1 3]]
arr2 shape:(3, 2)
=
[[13 29]
 [20 68]]
arr2 transpose:
[[2 4 1]
 [8 6 3]]


In [102]:
#np.sum
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.sum(arr))

#np.sum by row
arr1 = np.array([[1, 2, 3],[7, 1, 2]])
print(f"{arr1}")
print(f"sum by row {np.sum(arr1, axis=1)}")

#np.sum by column
print(f"sum by column {np.sum(arr1, axis=0)}")

21
[[1 2 3]
 [7 1 2]]
sum by row [ 6 10]
sum by column [8 3 5]


In [103]:
# Tính chuẩn Euclid của vector
arr = np.array([1, 2, 3])
print(np.linalg.norm(arr))

3.7416573867739413


In [106]:
#broadcasting array
arr1 = np.array([[1, 2, 3],[7, 1, 2]])
arr2 = np.array([1, 2, 3])
print(f"{arr1}")
print(f"arr1 shape:{arr1.shape}")

print("+")
print(f"{arr2}")
print(f"arr2 shape:{arr2.shape}")
print("=")
print(np.add(arr1, arr2))

num = 1
print(f"{arr1}")
print(f"arr1 shape:{arr1.shape}")

print("+")
print(f"{num}")
print(f"num shape:{np.array(num).shape}")
print("=")
print(np.add(arr1,num))

#also apply for array have multi dim or multi calculate



[[1 2 3]
 [7 1 2]]
arr1 shape:(2, 3)
+
[1 2 3]
arr2 shape:(3,)
=
[[2 4 6]
 [8 3 5]]
[[1 2 3]
 [7 1 2]]
arr1 shape:(2, 3)
+
1
num shape:()
=
[[2 3 4]
 [8 2 3]]


In [110]:
#apply_along_axis
arrx = np.array([[1, 2, 3],[7, 1, 2]])
print(arr)
print(np.apply_along_axis(np.sum, axis = 1, arr=arrx))

[1 2 3]
[ 6 10]


In [112]:
#vectorize
# aivietnam
import numpy as np

# Định ngh ĩa hàm chuy ển đổi nhiệt độ
def celsius_to_fahrenheit (c) :
  return (c * 9/5) + 32

# Vector hóa hàm celsius_to_fahrenheit
vectorized_conversion = np . vectorize(celsius_to_fahrenheit)
# Tạo mảng nhiệt độ Celsius
celsius = np . array ([0, 20, 37, 100])
# Áp dụng hàm vector hóa lên mảng
fahrenheit = vectorized_conversion(celsius)
print (" Chuyển đổi từ Celsius sang Fahrenheit :", fahrenheit)


 Chuyển đổi từ Celsius sang Fahrenheit : [ 32.   68.   98.6 212. ]
