## **Basic concept**

Basic concept about probability

In [1]:
import numpy as np

# Tao ra mang cac gia tri co kha nang xay ra
possibilities = np.array([0,1,2,3,4,5,6,7])

# So luong mau can sinh ra
size = 5

# Sinh ra cac mau ngau nhien
samples = np.random.choice(possibilities, size)

print(samples)

[3 1 5 4 3]


Uniform distribution (Phân phối đồng nhất)

In [8]:
# Thiet lap mot phan phoi dong nhat
low = 2 # Gioi han duoi
high = 5 # Gioi han tren
size = 5 # so luong mau

# Sinh ra cac mau ngau nhien
samples = np.random.uniform(low, high, size)

print(samples)

[2.06678022 4.44173262 4.12581722 3.07365941 3.70184615]


## **Coin toss problem**

In [11]:
import numpy as np
import random

# Total flips
total_flips = 10000

# number of heads appearing
total_heads = 0

# number of tails appearing
total_tails = 0

#
for i in range(total_flips):
  # randint(0,1) will return 0 or 1
  value = random.randint(0,1)
  if value == 0:
    total_heads += 1
  else:
    total_tails += 1

# Head probability
head_probability = total_heads / total_flips

# Tail probability
tail_probability = total_tails / total_flips

print("Total flips: ", total_flips)
print("Total heads: ", total_heads)
print("Total tails: ", total_tails)
print(f"Head probability: {head_probability}")
print(f"Tail probability: {tail_probability}")

Total flips:  10000
Total heads:  4963
Total tails:  5037
Head probability: 0.4963
Tail probability: 0.5037


## **The problem of estimating the number π**

In [14]:
import random
import math

n_loop = 10

for i in range(n_loop):
  rand_value = random.random() #Return random number between 0.0 and 1.0:
  print(rand_value)

0.9393815421719742
0.06646180811184166
0.7042836098983765
0.8245668697749668
0.5529968351849787
0.8654768662653554
0.979181180208132
0.7758951449252521
0.4498288767218599
0.6626467824088955


In [15]:
# Total point in square
Ns = 1000000

# Total point in circle
Nc = 0

# square edge
s = 2
# radius r = 1
# Point in square have coordinates (x,y) value [-1,1]

for i in range(Ns):
  x = random.random()*2 - 1
  y = random.random()*2 - 1
  # distance to center O(0,0)
  distance = math.sqrt(x**2 + y**2)
  if distance <= 1:
    Nc += 1

pi = (s**2) * Nc / Ns
print(f"pi = {pi}")


pi = 3.141044


## **Gaussian**

6.1 Set up Gaussian function with input is a number

In [ ]:
import math

In [19]:

def gaussian_with_input_number(x, mean = 0, standard_devitation = 1):
  result = 1/(standard_devitation * math.sqrt(2*math.pi))*math.exp((-(x -mean)**2)/(2*standard_devitation**2))
  return round(result,2)


6.2 Set up Gaussian function with input is a list

In [22]:
def gaussian_with_input_list(list, mean = 0, standard_devitation = 1):
  result = []
  for value in list:
    result.append(gaussian_with_input_number(value, mean, standard_devitation))
  return result

6.3 Set up Gaussian function with input is a numpy array

In [25]:
def gaussian_with_input_numpy_array(np_arr, mean = 0, standard_devitation = 1):
  result = []
  for value in np_arr:
    result.append(gaussian_with_input_number(value, mean, standard_devitation))
  return np.round(np.array(result),2)

Testing

In [20]:
# q1
x = 0.5
mean = 1
standard_devitation = 2
gaussian_with_input_number(x, mean, standard_devitation)

0.19

In [23]:
#q2
list = [-3, -0.4, 2]
mean = 0
standard_devitation = 2
gaussian_with_input_list(list, mean, standard_devitation)

[0.06, 0.2, 0.12]

In [26]:
#q3
np_arr = np.array([-0.1, 0.01, -3])
mean = 0
standard_devitation = 3
gaussian_with_input_numpy_array(np_arr, mean, standard_devitation)

array([0.13, 0.13, 0.08])

## **Classical Probability**

## **Basic**