### Step-by-step implementation

In [ ]:

data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [ ]:
# 1. data


print(X)


print(y)

[1.4 1.  1.5 3.1 3.8 4.1]
[0. 0. 0. 1. 1. 1.]


In [4]:
x_test = 2.4
print(x_test)

2.4


In [ ]:
# 2. distances


print(distances)

[1.  1.4 0.9 0.7 1.4 1.7]


In [ ]:

print(distances_sorted)

[3 2 0 1 4 5]


In [11]:
k = 3
print(distances_sorted[:k])


[3 2 0]


In [ ]:

print(values)

[1. 0. 0.]


In [ ]:


print(num_zeros)
print(num_ones)

2
1


In [ ]:
# get x
x_data = data['Petal_Length'].to_numpy()
print(x_data)

In [ ]:
# get y
y_data = data['Label'].to_numpy()
print(y_data)

In [ ]:
# test input (unknown y)
x_test = [2.4]

In [ ]:
# 1. compute distances
distances = np.sqrt( (x_data - x_test)**2 )
print(distances)

In [ ]:
# 2. get the top k
top_k = np.argsort(distances)
print(top_k)

k = 3
top_k = top_k[:k]
print(top_k)

In [ ]:
# get corresponding labels
values_top_k = y_data[top_k]
print(values_top_k)

In [ ]:
# get mojority
num_zeros = (values_top_k==0).sum()
print(num_zeros)

num_ones = (values_top_k==1).sum()
print(num_ones)

In [ ]:
# get mojority (2)

np.argsort(np.bincount(values_top_k.astype(int)))

### Way 1

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('iris_1D.csv')
x_data = data['Petal_Length'].to_numpy()
x_data = x_data.reshape(6, 1)

y_data = data['Label'].to_numpy()

# test input (unknown y)
x_test = [[2.4]]

In [ ]:
from sklearn import neighbors, datasets
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

In [ ]:
y_pred = classifier.predict(x_test)
print(y_pred)

### Way 2

In [ ]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

In [ ]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

In [ ]:
classifier.classes_

In [ ]:
y_data