M02W01D03- Review

In [1]:
import numpy as np

In [50]:
#q10
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
#10
slicing_data = data[:2, 1:]
slicing_data

array([[1, 2],
       [4, 5]])

In [52]:
slicing_data = slicing_data*3
slicing_data

array([[ 3,  6],
       [12, 15]])

In [38]:
#q9
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#q9
data[3:,:2]

array([[12, 13]])

In [42]:
#q9
data[3,2:]

array([14, 15])

In [40]:
#q9
data[:3,2]

array([ 2,  6, 10])

In [41]:
#q9
data[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [44]:
#q8
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
#q8
data[:,-1]

array([2, 5, 8])

In [46]:
#q8
data[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [47]:
#q8
data[:-1,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
#q8
data[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [53]:
#q7
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
#q7
data[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [55]:
#q7
data[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
#q6
data =np.arange(3,7)
out = data[[0,1,3,2]]
out

array([3, 4, 6, 5])

In [31]:
#q4
data = np.arange(6).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
#q4
data[:,1]

array([1, 4])

In [33]:
#q4
data[:,2]

array([2, 5])

In [34]:
#q4
data[1,:]

array([3, 4, 5])

In [22]:
data = np.array([1,2])
data
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2])

In [ ]:
data = np.array([1,2])
data
#np.reshape(data, (8,)) # failed cannot reshape arr 2, into 8,

In [3]:
data = np.arange(1, 3, 0.5)
print(data)

[1.  1.5 2.  2.5]


In [59]:
#q2
data = np.arange(10)
data.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
#q2
data = np.arange(10)
data.reshape(2, -1)#can only specify one unknown dimension

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
#q2
data = np.arange(10)
data.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
#q1
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [ ]:
np.arange(-3, 3, 0.5, dtype=int)
#now step is int so it will be round to 1

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])