### M02W01D03- Review

In [1]:
import numpy as np

In [16]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"before change: {data}")
np.append(data, [22,23])
print(f"after change: {data}")

before change: [ 1  2  3  4  5  6  7  8  9 10]
after change: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr_1=[6,8]
arr_2=[7,9]
np.append(arr_1,arr_2)

array([6, 8, 7, 9])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
data.sort()#axis ?
data

array([-9, -7, -3,  1,  2,  4,  5,  6,  8, 10])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
data.sort()#axis ?
data[::-1]#reverse

array([10,  8,  6,  5,  4,  2,  1, -3, -7, -9])

In [22]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
np.delete(data,2)

array([ 1,  2,  4,  5,  6, -7,  8, -9, 10])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
np.delete(data,np.arange(1,3))
#np.concatenate

array([ 1,  4,  5,  6, -7,  8, -9, 10])

In [33]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
r= np.where(data == -3)[0][0]#?
print(r)

2


In [41]:
x = np.linspace(1,5,5)
y = x[1:4]
y[-1] = 12345
print(f"x = {x}")
print(f"y = {x}")


x = [1.0000e+00 2.0000e+00 3.0000e+00 1.2345e+04 5.0000e+00]
y = [1.0000e+00 2.0000e+00 3.0000e+00 1.2345e+04 5.0000e+00]


In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
print(f"data = {data}")
# np.min
# np.max
# np.shape
# np.sum
# list have zip(), enumerate()
arr_1=np.array([6,8])
arr_2=np.array([7,9,4])
zip_arr = np.dstack((arr_1, arr_2))#????
#np.ndenumerate

In [ ]:
#Advance indexing
arr = np.array([[1,2], [3,4],[5,6]])
print(f"arr = {arr}")
print(arr.reshape(2,3))
#broadcasting when sum 2 array having different dimension
# it will broad array to fit the dimension

arr = [[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
print(f"data = {data}")

In [ ]:
arr_1=np.array([6,8])
arr_2=np.array([7,9,4])

In [73]:
np.array([1,2,3]) + np.array([[1],[2],[3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
# axis 1 column, 0 row
arr_1 = np.arange

In [ ]:
np.concatenate

In [ ]:
np.hstack

In [ ]:
np.vstack

In [ ]:
# element wise

In [ ]:
# Hadamard product



In [ ]:
#dot product

-----------------------------------------------------------------

In [42]:
#q10
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
#10
slicing_data = data[:2, 1:]
slicing_data

array([[1, 2],
       [4, 5]])

In [44]:
slicing_data = slicing_data*3
slicing_data

array([[ 3,  6],
       [12, 15]])

In [45]:
#q9
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
#q9
data[3:,:2]

array([[12, 13]])

In [47]:
#q9
data[3,2:]

array([14, 15])

In [48]:
#q9
data[:3,2]

array([ 2,  6, 10])

In [49]:
#q9
data[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [50]:
#q8
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
#q8
data[:,-1]

array([2, 5, 8])

In [52]:
#q8
data[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [53]:
#q8
data[:-1,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
#q8
data[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [55]:
#q7
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
#q7
data[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [57]:
#q7
data[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [58]:
#q6
data =np.arange(3,7)
out = data[[0,1,3,2]]
out

array([3, 4, 6, 5])

In [59]:
#q4
data = np.arange(6).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
#q4
data[:,1]

array([1, 4])

In [61]:
#q4
data[:,2]

array([2, 5])

In [62]:
#q4
data[1,:]

array([3, 4, 5])

In [63]:
data = np.array([1,2])
data
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2])

In [64]:
data = np.array([1,2])
data
#np.reshape(data, (8,)) # failed cannot reshape arr 2, into 8,

array([1, 2])

In [65]:
data = np.arange(1, 3, 0.5)
print(data)

[1.  1.5 2.  2.5]


In [66]:
#q2
data = np.arange(10)
data.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
#q2
data = np.arange(10)
data.reshape(2, -1)#can only specify one unknown dimension

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
#q2
data = np.arange(10)
data.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
#q1
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [70]:
np.arange(-3, 3, 0.5, dtype=int)
#now step is int so it will be round to 1

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])