### Numpy Baaic

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
print(arr)
arr = np.zeros(4)
print(arr)
arr = np.arange(1, 4, 2)
print(arr)
arr = np.random.rand(2)
print(arr)
arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.96198828 0.17346615]
[4.9e-324 9.9e-324 1.5e-323]


In [4]:
arr = np.array(
    [[1, 2, 3], [1, 2, 3]],
    dtype=float
)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


In [5]:
arr = np.array(
    [[1, 2, 3], [1, 2, 3]], dtype=float
)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)
print(arr.data)
arr

2
6
float64
(2, 3)
8


array([[1., 2., 3.],
       [1., 2., 3.]])

In [6]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr[0])

arr[1] = 3.0
print(arr)

print(arr[-4])

arr[-3] = 2.0
print(arr)

1.0
[1. 3. 3. 4.]
1.0
[1. 2. 3. 4.]


In [7]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]])

print(arr[0][3])
print(arr[-2][3])

arr[1] = 3.0
print(arr)

arr[0][-3] = 3.0
print(arr)

4.0
4.0
[[1. 2. 3. 4.]
 [3. 3. 3. 3.]]
[[1. 3. 3. 4.]
 [3. 3. 3. 3.]]


In [9]:
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
print(arr.shape)

arr = np.reshape(arr, (3, 2))
print(arr)
print(arr.shape)

arr = np.reshape(arr, (3, 3)) # Error

(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


ValueError: cannot reshape array of size 6 into shape (3,3)

In [10]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 6.0, 7.0, 8.0])

print(arr1 + arr2)
print(np.add(arr1, arr2))

print(arr1 % arr2)
print(np.mod(arr1, arr2))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [8]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr[0])
print(arr[0][0::2])

print(arr[0:2,1:3])
print(arr[0:2,-4::2])

[1. 2. 3. 4.]
[1. 3.]
[[2. 3.]
 [6. 7.]]
[[1. 3.]
 [5. 7.]]


In [12]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 2.0, 7.0, 8.0])

print("1",arr1 < arr2)
print("2",np.less(arr1, arr2))

print("3",arr1 != arr2)
print("4",np.not_equal(arr1, arr2))

np.logical_or(
    np.less(arr1, arr2),
    np.not_equal(arr1, arr2)
)

1 [ True False  True  True]
2 [ True False  True  True]
3 [ True False  True  True]
4 [ True False  True  True]


array([ True, False,  True,  True])

In [13]:
arr = np.random.rand(2, 3)
print(arr)

print(np.sin(arr))

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[[0.13339227 0.55708349 0.05167098]
 [0.40646599 0.20924872 0.67921631]]
[[0.13299703 0.52871292 0.05164799]
 [0.39536573 0.20772507 0.62818345]]
[[0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(np.max(arr))

arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])
print(np.max(arr))
print(np.max(arr, axis=0))#col
print(np.max(arr, axis=1))#row

4.0
8.0
[5. 6. 7. 8.]
[4. 8.]


In [15]:
arr1 = np.array(['Iphone: ', 'Price: '])
arr2 = np.array(['15', '$900'])

print(np.char.add(arr1, arr2))
print(np.char.multiply(arr1, 3))
print(np.char.upper(arr1))
print(np.char.equal(arr1, arr2))

['Iphone: 15' 'Price: $900']
['Iphone: Iphone: Iphone: ' 'Price: Price: Price: ']
['IPHONE: ' 'PRICE: ']
[False False]


In [ ]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([[1.0], [5.0]])

print("1:", arr1)
print("2:",arr2)

print("3:",np.add(arr1, 3.0))
#### NOTICE!!!
print("4:",np.add(arr1, arr2))

1: [1. 2. 3. 4.]
2: [[1.]
 [5.]]
3: [4. 5. 6. 7.]
4: [[2. 3. 4. 5.]
 [6. 7. 8. 9.]]


In [18]:
arr = np.array([1., 2., 3.])
print(np.dot(arr, 2))

[2. 4. 6.]


In [19]:
arr_1 = np.array([1., 2., 3.])
arr_2 = np.array([1., 2., 1.])
print(np.dot(arr_1, arr_2))

8.0


In [20]:
arr_1 = np.array([
    [3., 4., 1.], [4., 3., 2.]
])
arr_2 = np.array([
    [1., 2.], [0., 1.], [2., 0.]
])
print(np.dot(arr_1, arr_2))

[[ 5. 10.]
 [ 8. 11.]]


In [22]:
arr = np.array([
    [1, 2, 3], [3, 4, 5]
])

print("1: ", np.transpose(arr))
print("2: ", np.transpose(arr).shape)

print("3: ", arr.flatten())
print("4: ", arr.flatten().shape)

1:  [[1 3]
 [2 4]
 [3 5]]
2:  (3, 2)
3:  [1 2 3 3 4 5]
4:  (6,)


### M02W01D03- Review

In [1]:
import numpy as np

In [16]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"before change: {data}")
np.append(data, [22,23])
print(f"after change: {data}")

before change: [ 1  2  3  4  5  6  7  8  9 10]
after change: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr_1=[6,8]
arr_2=[7,9]
np.append(arr_1,arr_2)

array([6, 8, 7, 9])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
data.sort()#axis ?
data

array([-9, -7, -3,  1,  2,  4,  5,  6,  8, 10])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
data.sort()#axis ?
data[::-1]#reverse

array([10,  8,  6,  5,  4,  2,  1, -3, -7, -9])

In [22]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
np.delete(data,2)

array([ 1,  2,  4,  5,  6, -7,  8, -9, 10])

In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
np.delete(data,np.arange(1,3))
#np.concatenate

array([ 1,  4,  5,  6, -7,  8, -9, 10])

In [33]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
r= np.where(data == -3)[0][0]#?
print(r)

2


In [41]:
x = np.linspace(1,5,5)
y = x[1:4]
y[-1] = 12345
print(f"x = {x}")
print(f"y = {x}")


x = [1.0000e+00 2.0000e+00 3.0000e+00 1.2345e+04 5.0000e+00]
y = [1.0000e+00 2.0000e+00 3.0000e+00 1.2345e+04 5.0000e+00]


In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
print(f"data = {data}")
# np.min
# np.max
# np.shape
# np.sum
# list have zip(), enumerate()
arr_1=np.array([6,8])
arr_2=np.array([7,9,4])
zip_arr = np.dstack((arr_1, arr_2))#????
#np.ndenumerate

In [ ]:
#Advance indexing
arr = np.array([[1,2], [3,4],[5,6]])
print(f"arr = {arr}")
print(arr.reshape(2,3))
#broadcasting when sum 2 array having different dimension
# it will broad array to fit the dimension

arr = [[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
data = np.array([1,2,-3,4,5,6,-7,8,-9,10])
print(f"data = {data}")

In [ ]:
arr_1=np.array([6,8])
arr_2=np.array([7,9,4])

In [73]:
np.array([1,2,3]) + np.array([[1],[2],[3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
# axis 1 column, 0 row
arr_1 = np.arange

In [ ]:
np.concatenate

In [ ]:
np.hstack

In [ ]:
np.vstack

In [ ]:
# element wise

In [ ]:
# Hadamard product



In [ ]:
#dot product

-----------------------------------------------------------------

In [42]:
#q10
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
#10
slicing_data = data[:2, 1:]
slicing_data

array([[1, 2],
       [4, 5]])

In [44]:
slicing_data = slicing_data*3
slicing_data

array([[ 3,  6],
       [12, 15]])

In [45]:
#q9
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
#q9
data[3:,:2]

array([[12, 13]])

In [47]:
#q9
data[3,2:]

array([14, 15])

In [48]:
#q9
data[:3,2]

array([ 2,  6, 10])

In [49]:
#q9
data[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [50]:
#q8
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
#q8
data[:,-1]

array([2, 5, 8])

In [52]:
#q8
data[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [53]:
#q8
data[:-1,:]

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
#q8
data[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [55]:
#q7
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
#q7
data[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [57]:
#q7
data[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [58]:
#q6
data =np.arange(3,7)
out = data[[0,1,3,2]]
out

array([3, 4, 6, 5])

In [59]:
#q4
data = np.arange(6).reshape(2,3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
#q4
data[:,1]

array([1, 4])

In [61]:
#q4
data[:,2]

array([2, 5])

In [62]:
#q4
data[1,:]

array([3, 4, 5])

In [63]:
data = np.array([1,2])
data
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2])

In [64]:
data = np.array([1,2])
data
#np.reshape(data, (8,)) # failed cannot reshape arr 2, into 8,

array([1, 2])

In [65]:
data = np.arange(1, 3, 0.5)
print(data)

[1.  1.5 2.  2.5]


In [66]:
#q2
data = np.arange(10)
data.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
#q2
data = np.arange(10)
data.reshape(2, -1)#can only specify one unknown dimension

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
#q2
data = np.arange(10)
data.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
#q1
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [70]:
np.arange(-3, 3, 0.5, dtype=int)
#now step is int so it will be round to 1

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])