## Simple Classification

In [ ]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB



In [8]:
prediction

array([1])

In [9]:
prediction_proba

array([[0.4, 0.6]])

In [11]:
np.exp(model.class_log_prior_)

array([0.5, 0.5])

In [13]:
# Empirical log probability of features given a class, P(x_i|y)
np.exp(model.feature_log_prob_)

array([[0.4],
       [0.6]])