<a href="https://colab.research.google.com/github/mylethidiem/zero-to-hero/blob/main/preAIO25/AIOCodeMathDA/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[AIO2025] LẬP TRÌNH - TOÁN - DATA ANALYSIS \
LÊ THỊ DIỄM MY

# Day 1̉6: Gram Matrix in Style transfer
---



Set up Gram Matrix by using Numpy

In [1]:
import numpy as np

def compute_gram_matrix(feature_map: np.ndarray) -> np.ndarray:
  """
  Compute Gram Matrix from feature map
  Args: feature_map(np.ndarray) matrix size (C, H, W)
  Returns: (np.ndarray) Gram matrix size (C, C)
  """
  # Get size of input
  C, H, W = feature_map.shape

  # Convert matrix to shape (C, H*W)
  F = feature_map.reshape(C, H*W)

  # Calculate Gram Matrix G = F <dot product> F.T
  G = np.dot(F, F.transpose())

  # Normalise by pixel count
  G /= H * W

  return G

In [2]:
# Generate data set with size (3, 4, 4)
np.random.seed(42)
feature_map = np.random.rand(3, 4, 4)

# Compute Gram Matrix
grand_matrix = compute_gram_matrix(feature_map)

# Print result
print(f"Compute Gram Matrix: \n{grand_matrix}")

Compute Gram Matrix: 
[[0.33432857 0.2207897  0.27598961]
 [0.2207897  0.19580158 0.19452994]
 [0.27598961 0.19452994 0.32603015]]


Set up Gram Matrix by using Pytorch

## Exercise:

# Day 17: Getting Started with WandB


---



# Day 18

# Day 19

# Day 20