In [8]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
corpus = [
    "AI is efficient",
    "fast and efficient algorithm",
    "highly accurate and fast",
    "coding AI is challenging",
    "AI may produce errors",
    "unpredictable results"
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X = X.toarray()

#
y_data = np.array([1, 1, 1, 0, 0, 0])

# dictionary
dictionary_ = ["accurate","ai","algorithm","and","challenging","coding","efficient","errors","fast","highly","is","may","produce","results","unpredictable"]

list_vector = []
for data1, vector in zip(corpus, X):
    for word in data1.lower().split():
        index = dictionary_.index(word)
        assert vector[index] == 1
    print(vector)
    list_vector.append(vector)

data1 =  "AI is efficient"

# data1 to feature vector
vector_data1 = [0,	1,	0,	0,	0,	0,	1,	0,	0,	0,	1,	0,	0,	0,	0]

[0 1 0 0 0 0 1 0 0 0 1 0 0 0 0]
[0 0 1 1 0 0 1 0 1 0 0 0 0 0 0]
[1 0 0 1 0 0 0 0 1 1 0 0 0 0 0]
[0 1 0 0 1 1 0 0 0 0 1 0 0 0 0]
[0 1 0 0 0 0 0 1 0 0 0 1 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]


Các văn bản and	Nhãn \
AI is efficient	1 \
fast and efficient algori thm	1 \
highly accurate and fast	1 \
coding AI is challenging	0 \
AI may produce errors	0 \
unpredictable results	0 

In [ ]:
data2 = "AI is accurate and fast"
# vector_data2
vector_data2 =  [1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]

# Euclid
distance = np.sqrt(np.sum((np.array(vector_data1) - np.array(vector_data2))**2))
distance

2.0

In [13]:

for v in list_vector:
    euclid_distance = np.sqrt(np.sum((np.array(vector_data2) - np.array(v))**2))
    print(euclid_distance)
    # euclid_distance.sort()


2.0
2.23606797749979
1.7320508075688772
2.23606797749979
2.6457513110645907
2.6457513110645907


In [5]:
!gdown 1z99FO2PE35V2BHGC4oy_qC7iKYDFy8pH
import pandas as pd
df = pd.read_csv('my_data.csv')
X_train = df[["perimeter_mean", "area_mean", "compactness_mean"]].values.tolist()
labels = df['diagnosis'].values.tolist()

Downloading...
From: https://drive.google.com/uc?id=1z99FO2PE35V2BHGC4oy_qC7iKYDFy8pH
To: /home/banhmuy/zero-to-hero/AIO2025/M03/my_data.csv
100%|███████████████████████████████████████████| 220/220 [00:00<00:00, 822kB/s]


In [6]:
y_train = []
for label in labels:
    if label == "B":
        y_train.append(0)
    else:
        y_train.append(1)

print(type(y_train))
y_train

<class 'list'>


[0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

In [7]:
train_data = zip(X_train, y_train)
train_data = list(train_data)
train_data


[([0.28, 0.17, 0.12], 0),
 ([0.11, 0.06, 0.16], 0),
 ([0.33, 0.21, 0.2], 0),
 ([0.26, 0.15, 0.09], 0),
 ([0.22, 0.09, 0.2], 0),
 ([0.58, 0.41, 0.47], 1),
 ([0.57, 0.37, 0.77], 1),
 ([0.48, 0.38, 0.27], 1),
 ([0.6, 0.48, 0.37], 1),
 ([0.54, 0.42, 0.43], 1)]

In [8]:
import numpy as np

first_three = X_train[:3]
x=[0.25, 0.25, 0.25]
distances = []
for point in first_three:
    manhattan_dist = sum(abs(x[i] - point[i]) for i in range(3))
    distances.append(manhattan_dist)

print(distances)

[0.24000000000000002, 0.42000000000000004, 0.17]


In [9]:
import numpy as np

x = [0.25, 0.25, 0.25]
distances = []

# Calculate Manhattan distances and store with their labels
for point, label in zip(X_train, y_train):
    manhattan_dist = sum(abs(x[i] - point[i]) for i in range(3))
    distances.append((manhattan_dist, label))

# Sort by distance
sorted_distances = sorted(distances, key=lambda x: x[0])

# Take top K=7
top_k = sorted_distances[:7]

# Count classes
class_0 = sum(1 for _, label in top_k if label == 0)
class_1 = sum(1 for _, label in top_k if label == 1)

print(f"In top K=7 neighbors:")
print(f"Class 0: {class_0}")
print(f"Class 1: {class_1}")


In top K=7 neighbors:
Class 0: 5
Class 1: 2


In [10]:
import numpy as np

C1 = np.array([0.33, 0.21, 0.2])
total_distance = 0

# Tính tổng khoảng cách Euclidean từ mỗi điểm đến C1
for point in X_train:
    dist = np.sqrt(np.sum((np.array(point) - C1)**2))
    total_distance += dist

# Làm tròn kết quả đến 2 chữ số thập phân
total_distance = round(total_distance, 2)

print(f"Tổng khoảng cách Euclidean đến C1: {total_distance}")

Tổng khoảng cách Euclidean đến C1: 2.77


In [11]:
import numpy as np

C2 = np.array([0.6, 0.48, 0.37])
total_distance = 0

# Tính tổng khoảng cách Euclidean từ mỗi điểm đến C2
for point in X_train:
    dist = np.sqrt(np.sum((np.array(point) - C2)**2))
    total_distance += dist

# Làm tròn kết quả đến 2 chữ số thập phân
total_distance = round(total_distance, 2)

print(f"Tổng khoảng cách Euclidean đến C2: {total_distance}")

Tổng khoảng cách Euclidean đến C2: 3.56


In [ ]:
import numpy as np

C1 = np.array([0.33, 0.21, 0.2])
C2 = np.array([0.6, 0.48, 0.37])

# Vector để lưu nhãn cụm cho từng điểm
cluster_labels = []

# Phân cụm dựa trên khoảng cách gần nhất
for point in X_train:
    # Tính khoảng cách tới cả 2 tâm
    dist_to_c1 = np.sqrt(np.sum((np.array(point) - C1)**2))
    dist_to_c2 = np.sqrt(np.sum((np.array(point) - C2)**2))

    # Gán nhãn 0 nếu gần C1 hơn, 1 nếu gần C2 hơn
    cluster = 0 if dist_to_c1 < dist_to_c2 else 1
    cluster_labels.append(cluster)

# Chuyển sang numpy array để dễ xem
cluster_labels = np.array(cluster_labels)
print("Vector phân cụm:")
print(cluster_labels)

Vector phân cụm:
[0 0 0 0 0 1 1 1 1 1]


In [13]:
import numpy as np

# Tách các điểm theo cụm
cluster_0_points = [point for point, label in zip(X_train, cluster_labels) if label == 0]
cluster_1_points = [point for point, label in zip(X_train, cluster_labels) if label == 1]

# Tính tâm mới cho mỗi cụm (trung bình của các điểm trong cụm)
new_C1 = np.mean(cluster_0_points, axis=0)
new_C2 = np.mean(cluster_1_points, axis=0)

# Làm tròn đến 2 chữ số thập phân
new_C1 = np.round(new_C1, 2)
new_C2 = np.round(new_C2, 2)

print("Tọa độ mới của tâm cụm 1:")
print(new_C1)
print("\nTọa độ mới của tâm cụm 2:")
print(new_C2)

Tọa độ mới của tâm cụm 1:
[0.24 0.14 0.15]

Tọa độ mới của tâm cụm 2:
[0.55 0.41 0.46]


In [ ]:
import numpy as np

# Sử dụng tọa độ tâm cụm mới đã tính được
new_C1 = new_C1  # Tâm cụm 1 mới
new_C2 = new_C2  # Tâm cụm 2 mới

# Vector để lưu nhãn cụm mới cho từng điểm
new_cluster_labels = []

# Phân cụm dựa trên khoảng cách gần nhất tới tâm mới
for point in X_train:
    # Tính khoảng cách tới cả 2 tâm mới
    dist_to_c1 = np.sqrt(np.sum((np.array(point) - new_C1)**2))
    dist_to_c2 = np.sqrt(np.sum((np.array(point) - new_C2)**2))

    # Gán nhãn 0 nếu gần C1 mới hơn, 1 nếu gần C2 mới hơn
    cluster = 0 if dist_to_c1 < dist_to_c2 else 1
    new_cluster_labels.append(cluster)

# Chuyển sang numpy array để dễ xem
new_cluster_labels = np.array(new_cluster_labels)
print("Vector phân cụm mới:")
print(new_cluster_labels)

Vector phân cụm mới:
[0 0 0 0 0 1 1 1 1 1]


In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

corpus = [
    "AI is efficient",
    "fast and efficient algorithm",
    "highly accurate and fast",
    "coding AI is challenging",
    "AI may produce errors",
    "unpredictable results"
]
dictionary_ = ["accurate","ai","algorithm","and","challenging","coding","efficient","errors","fast","highly","is","may","produce","results","unpredictable"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X = X.toarray()
c1 = "AI is efficient"
c2 = "AI may produce errors"

In [ ]:
# Convert c1 to vector based on dictionary ????
c1_vector = [0] * len(dictionary_)
for word in c1.lower().split():
    if word in dictionary_:
        index = dictionary_.index(word)
        c1_vector[index] = 1

# Calculate Euclidean distances to samples 1,2,3,5
samples = [0, 1, 2, 4]  # indices for samples 1,2,3,5 (0-based indexing)
distances = []

for i in samples:
    dist = np.sqrt(np.sum((np.array(c1_vector) - X[i])**2))
    distances.append(round(dist, 3))

print("Euclidean distances from c1 to samples 1,2,3,5:")
for i, d in enumerate(distances, 1):
    if i == 4:  # For sample 5
        print(f"Sample 5: {d}")
    else:
        print(f"Sample {i}: {d}")

Euclidean distances from c1 to samples 1,2,3,5:
Sample 1: 0.0
Sample 2: 2.236
Sample 3: 2.646
Sample 5: 2.236


In [2]:
from sklearn.cluster import KMeans
import numpy as np

# Apply K-means clustering with k=2
kmeans = KMeans(n_clusters=2, random_state=42)
cluster_labels = kmeans.fit_predict(X)

# Print the cluster assignments for each document
print("Cluster assignments (0 or 1) for each document:")
for doc, label in zip(corpus, cluster_labels):
    print(f"{doc}: Cluster {label}")

print("\nCluster vector:")
print(cluster_labels)

Cluster assignments (0 or 1) for each document:
AI is efficient: Cluster 1
fast and efficient algorithm: Cluster 0
highly accurate and fast: Cluster 0
coding AI is challenging: Cluster 1
AI may produce errors: Cluster 1
unpredictable results: Cluster 1

Cluster vector:
[1 0 0 1 1 1]


In [3]:
# Convert centers to vectors
c1_vector = [0] * len(dictionary_)
for word in c1.lower().split():
    if word in dictionary_:
        index = dictionary_.index(word)
        c1_vector[index] = 1

c2_vector = [0] * len(dictionary_)
for word in c2.lower().split():
    if word in dictionary_:
        index = dictionary_.index(word)
        c2_vector[index] = 1

# Calculate distances to both centers for each point and assign clusters
cluster_vector = []
for point in X:
    dist_to_c1 = np.sqrt(np.sum((np.array(c1_vector) - point)**2))
    dist_to_c2 = np.sqrt(np.sum((np.array(c2_vector) - point)**2))
    # Assign to cluster 0 if closer to c1, cluster 1 if closer to c2
    cluster = 0 if dist_to_c1 < dist_to_c2 else 1
    cluster_vector.append(cluster)

print("Cluster assignments:")
for doc, cluster in zip(corpus, cluster_vector):
    print(f"{doc}: Cluster {cluster}")

print("\nCluster vector:")
print(np.array(cluster_vector))

Cluster assignments:
AI is efficient: Cluster 0
fast and efficient algorithm: Cluster 0
highly accurate and fast: Cluster 0
coding AI is challenging: Cluster 0
AI may produce errors: Cluster 1
unpredictable results: Cluster 0

Cluster vector:
[0 0 0 0 1 0]


In [4]:
# Tách các điểm theo cụm
cluster_0_points = [X[i] for i in range(len(X)) if cluster_vector[i] == 0]
cluster_1_points = [X[i] for i in range(len(X)) if cluster_vector[i] == 1]

# Tính tâm mới cho mỗi cụm
new_c1_center = np.mean(cluster_0_points, axis=0)
new_c2_center = np.mean(cluster_1_points, axis=0)

# Làm tròn đến 1 chữ số thập phân
new_c1_center = np.round(new_c1_center, 1)
new_c2_center = np.round(new_c2_center, 1)

print("Tọa độ tâm cụm 1 (làm tròn 1 chữ số):")
print(new_c1_center)
print("\nTọa độ tâm cụm 2 (làm tròn 1 chữ số):")
print(new_c2_center)

# In ra các từ có tọa độ khác 0 cho mỗi tâm cụm
print("\nCác từ có trọng số khác 0 trong tâm cụm 1:")
for i, value in enumerate(new_c1_center):
    if value > 0:
        print(f"{dictionary_[i]}: {value}")

print("\nCác từ có trọng số khác 0 trong tâm cụm 2:")
for i, value in enumerate(new_c2_center):
    if value > 0:
        print(f"{dictionary_[i]}: {value}")

Tọa độ tâm cụm 1 (làm tròn 1 chữ số):
[0.2 0.4 0.2 0.4 0.2 0.2 0.4 0.  0.4 0.2 0.4 0.  0.  0.2 0.2]

Tọa độ tâm cụm 2 (làm tròn 1 chữ số):
[0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]

Các từ có trọng số khác 0 trong tâm cụm 1:
accurate: 0.2
ai: 0.4
algorithm: 0.2
and: 0.4
challenging: 0.2
coding: 0.2
efficient: 0.4
fast: 0.4
highly: 0.2
is: 0.4
results: 0.2
unpredictable: 0.2

Các từ có trọng số khác 0 trong tâm cụm 2:
ai: 1.0
errors: 1.0
may: 1.0
produce: 1.0


KDTree


In [1]:
import numpy as np

# Dữ liệu để xây dựng cây quyết định (11 dòng đầu tiên)
train_data = np.array([
    ['Sunny', 'Cool', 'High', 'Weak', 'Yes'],
    ['Sunny', 'Cool', 'High', 'Strong', 'No'],
    ['Overcast', 'Mild', 'High', 'Weak', 'Yes'],
    ['Rain', 'Hot', 'Normal', 'Weak', 'Yes'],
    ['Rain', 'Hot', 'Normal', 'Strong', 'No'],
    ['Overcast', 'Hot', 'Normal', 'Strong', 'Yes'],
    ['Sunny', 'Mild', 'High', 'Weak', 'No'],
    ['Sunny', 'Cool', 'Normal', 'Weak', 'Yes'],
    ['Sunny', 'Hot', 'High', 'Weak', 'No'],
    ['Rain', 'Cool', 'Normal', 'Weak', 'Yes'],
    ['Rain', 'Cool', 'High', 'Strong', 'No']
])

# Dữ liệu kiểm tra (3 dòng còn lại)
test_data = np.array([
    ['Sunny', 'Cool', 'Normal', 'Strong', 'Yes'],
    ['Overcast', 'Hot', 'High', 'Strong', 'Yes'],
    ['Overcast', 'Mild', 'Normal', 'Weak', 'Yes']
])

print("Kích thước dữ liệu huấn luyện:", train_data.shape)
print("Kích thước dữ liệu kiểm tra:", test_data.shape)


Kích thước dữ liệu huấn luyện: (11, 5)
Kích thước dữ liệu kiểm tra: (3, 5)


In [ ]:
# !pip install gradio
# conda install -c conda-forge gradio
# it cause crash sometimes so please install in cmd instead of VS Code

In [2]:
import numpy as np
from collections import Counter
import gradio as gr

# Tính Entropy
def entropy(y):
    counter = Counter(y)
    probs = [count/len(y) for count in counter.values()]
    return -sum(p * np.log2(p) for p in probs)

# Tính Information Gain
def information_gain(X, y, feature_idx):
    parent_entropy = entropy(y)

    # Tính entropy cho mỗi giá trị của feature
    values = set(X[:, feature_idx])
    weighted_entropy = 0
    for value in values:
        mask = X[:, feature_idx] == value
        child_y = y[mask]
        weight = len(child_y) / len(y)
        weighted_entropy += weight * entropy(child_y)

    return parent_entropy - weighted_entropy

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
        self.feature = feature  # index của feature để split
        self.threshold = threshold  # giá trị của feature để split
        self.left = left  # node con trái
        self.right = right  # node con phải
        self.value = value  # giá trị dự đoán tại node lá

class DecisionTree:
    def __init__(self, max_depth=None):
        self.max_depth = max_depth
        self.root = None
        self.feature_names = None

    def fit(self, X, y, feature_names=None):
        self.feature_names = feature_names
        self.n_classes = len(np.unique(y))
        self.root = self._grow_tree(X, y)

    def _grow_tree(self, X, y, depth=0):
        n_samples, n_features = X.shape

        # Điều kiện dừng
        if (self.max_depth is not None and depth >= self.max_depth) or len(np.unique(y)) == 1:
            return Node(value=Counter(y).most_common(1)[0][0])

        # Tìm feature tốt nhất để split
        best_feature = None
        best_gain = -1

        for feature_idx in range(n_features):
            gain = information_gain(X, y, feature_idx)
            if gain > best_gain:
                best_gain = gain
                best_feature = feature_idx

        if best_gain == 0:
            return Node(value=Counter(y).most_common(1)[0][0])

        # Tạo node và chia dữ liệu
        node = Node(feature=best_feature)

        unique_values = np.unique(X[:, best_feature])
        for value in unique_values:
            mask = X[:, best_feature] == value
            if sum(mask) > 0:
                child_X = X[mask]
                child_y = y[mask]
                if node.threshold is None:
                    node.threshold = value
                    node.left = self._grow_tree(child_X, child_y, depth + 1)
                else:
                    node.right = self._grow_tree(child_X, child_y, depth + 1)

        return node

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.root) for x in X])

    def _traverse_tree(self, x, node):
        if node.value is not None:
            return node.value

        if x[node.feature] == node.threshold:
            return self._traverse_tree(x, node.left)
        return self._traverse_tree(x, node.right)

    def visualize(self, node=None, depth=0, prefix=""):
        if node is None:
            node = self.root

        result = ""

        if node.value is not None:
            result += prefix + f"Predict: {node.value}\n"
            return result

        feature_name = f"Feature {node.feature}" if self.feature_names is None else self.feature_names[node.feature]
        result += prefix + f"{feature_name} = {node.threshold}?\n"

        result += self.visualize(node.left, depth + 1, prefix + "├── Yes: ")
        result += self.visualize(node.right, depth + 1, prefix + "└── No: ")

        return result

# Tạo giao diện Gradio
def train_and_visualize(X_str, feature_names_str):
    try:
        # Chuyển đổi input string thành numpy array
        X_lines = X_str.strip().split('\n')
        X = np.array([line.strip().split(',') for line in X_lines])

        # Tách features và labels
        features = X[:, :-1]
        labels = X[:, -1]

        # Chuyển đổi tên features
        feature_names = feature_names_str.strip().split(',')

        # Huấn luyện cây quyết định
        tree = DecisionTree(max_depth=5)
        tree.fit(features, labels, feature_names)

        # Trả về visualization
        return tree.visualize()
    except Exception as e:
        return f"Error: {str(e)}"

# Tạo giao diện
iface = gr.Interface(
    fn=train_and_visualize,
    inputs=[
        gr.Textbox(label="Enter training data (CSV format, last column is label)"),
        gr.Textbox(label="Enter feature names (comma-separated)")
    ],
    outputs=gr.Textbox(label="Decision Tree Visualization"),
    title="Decision Tree Visualizer",
    description="Enter your training data and feature names to visualize the decision tree"
)

# Chạy giao diện
# Add share=True to create a public link
iface.launch(share=True)

/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/gradio/routes.py", line 713, in main
    resp = templates.TemplateResponse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 209, in TemplateResponse
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 132, in get_template
    return self.env.get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/pyth

* Running on local URL:  http://127.0.0.1:7860


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/gradio/routes.py", line 713, in main
    resp = templates.TemplateResponse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 209, in TemplateResponse
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 132, in get_template
    return self.env.get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/jinja2/environment.py", line 975,

* Running on public URL: https://1335a607a1c90faf33.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/gradio/routes.py", line 713, in main
    resp = templates.TemplateResponse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 209, in TemplateResponse
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/starlette/templating.py", line 132, in get_template
    return self.env.get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/banhmuy/miniconda3/envs/ds_env/lib/python3.11/site-packages/jinja2/environment.py", line 975,

KeyboardInterrupt: 