## Simple Classification

In [7]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

# Data: Studied (1 for Yes, 0 for No) and Result (1 for Pass, 0 for Fail)
X = np.array([[0], [0], [1], [1], [1], [0]])
y = np.array([0, 1, 0, 1, 1, 0])

# Create and train the model
model = BernoulliNB()
model.fit(X, y)

# Predict the result for a student who studied
new_data = np.array([[1]])
prediction = model.predict(new_data)
prediction_proba = model.predict_proba(new_data)

In [2]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

# Data: Studied (1 for Yes, 0 for No)
# and Result (1 for Pass, 0 for Fail)
X = np.array([[0], [0], [1], [1], [1], [0]])
y = np.array([0, 1, 0, 1, 1, 0])

# Create and train the model
model = BernoulliNB()
model.fit(X,y)

# Predict the result for a student who studied
new_data = np.array([[1]])
prediction = model.predict(new_data)
prediction_probability = model.predict_proba(new_data)

print("prediction = %f" % prediction)
print(prediction_probability)

prediction = 1.000000
[[0.4 0.6]]


/tmp/ipykernel_86707/3859852243.py:18: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print("prediction = %f" % prediction)


In [3]:
np.exp(model.class_log_prior_)

array([0.5, 0.5])

In [13]:
# Empirical log probability of features given a class, P(x_i|y)
np.exp(model.feature_log_prob_)

array([[0.4],
       [0.6]])