<a href="https://colab.research.google.com/github/mylethidiem/zero-to-hero/blob/main/AIO2025/M01W03_Exercise_OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Exercise 1**

In [ ]:
import torch
import torch.nn as nn

In [ ]:
data = None
data

In [ ]:
softmax_function = None
output = None
output

## **Exercise 2, 3**

In [ ]:
import torch.nn as nn

class MySigmoid(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

# Create an instance of the custom sigmoid class
my_sigmoid = MySigmoid()

In [ ]:
# input data
x = torch.tensor([1, 5, -4, 3, -2])

# sigmoid function
output = my_sigmoid(x)
print(output)

tensor([0.7311, 0.9933, 0.0180, 0.9526, 0.1192])


## **Exercise 4**

In [ ]:
import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        ### Your Code Here
        max_val = torch.max(x, dim=-1, keepdim=True).values
        numerator = torch.exp(x - max_val)
        denominator = torch.sum(numerator, dim=-1, keepdim=True)
        return numerator / denominator
        ### End Code Here

data = torch.Tensor([1, 5, -4, 3, -2])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
output

tensor([1.5862e-02, 8.6604e-01, 1.0688e-04, 1.1721e-01, 7.8972e-04])

## **Exercise 5, 6, 7**

In [72]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass


class Student(Person):
    def __init__(self, name:str="", yob:int=0, grade:str=""):
        ### Your Code Here
        super().__init__(name, yob)
        self.grade = grade
        ### End Code Here

    def describe(self):
        print(f"Student name {self._name}, year of birth: {self._yob}")


class Teacher(Person):
    def __init__(self, name:str="", yob:int=0, subject:str=""):
        ### Your Code Here
        super().__init__(name, yob)
        self.__subject = subject
        ### End Code Here

    def describe(self):
        print(f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.__subject}")

class Doctor(Person):
    def __init__(self, name:str="", yob:int=0, specialist:str=""):
        ### Your Code Here
        super().__init__(name, yob)
        self.__specialist = specialist
        ### End Code Here

    def describe(self):
        print(f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self.__specialist}")

In [67]:
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()

teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()

doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()

Student name studentA, year of birth: 2010


## **Exercise 8**

In [73]:
# import datetime

class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__list_people = list()

    def add_person(self, person:Person):
        self.__list_people.append(person)

    def describe(self):
        ### Your Code Here
        print(f"Ward Name: {self.__name}")
        for people in self.__list_people:
          people.describe()
        ### End Code Here

    def count_doctor(self):
        ### Your Code Here
        num_doctor = 0
        for people in self.__list_people:
          if isinstance(people, Doctor):
            num_doctor += 1
        return num_doctor
        ### End Code

    def count_teacherT(self):
        ### Your Code Here
        num_teacher = 0
        for people in self.__list_people:
          if isinstance(people, Teacher):
            num_teacher += 1
        return num_teacher
        ### End Code Here

    def sort_age(self):
        ### Your Code Here
        self.__list_people.sort(key=lambda person: person.get_yob(), reverse=True)
        ### End Code Here

    def compute_average(self):
        ### Your Code Here
        # current_year = datetime.date.today().year
        sum_teacher_years = 0
        num_teacher = 0
        for people in self.__list_people:
          if isinstance(people, Teacher):
            num_teacher += 1
            # sum_teacher_age += (current_year - people.get_yob())
            sum_teacher_years += people.get_yob()

        if num_teacher == 0:
          print("No teacher in list!")
          return 0

        return sum_teacher_years / num_teacher
        ### End Code Here

In [74]:
# 2(a)
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()

teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()

doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()


# 2(b)
print()
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

# 2(c)
print(f"\nNumber of doctors: {ward1.count_doctor()}")

# 2(d)
print("\nAfter sorting Age of Ward1 people")
ward1.sort_age()
ward1.describe()

# 2(e)
print(f"\nAverage year of birth (teachers): {ward1.compute_average()}")

Student name studentA, year of birth: 2010
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists

Ward Name: Ward1
Student name studentA, year of birth: 2010
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists

Number of doctors: 2

After sorting Age of Ward1 people
Ward Name: Ward1
Student name studentA, year of birth: 2010
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists

Average year of birth (teachers): 1982.0


## **Exercise 9**

In [ ]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        ### Your Code Here
        return not self.__stack
        ### End Code Here

    def is_full(self):
        ### Your Code Here
        return len(self.__stack) == self.__capacity
        ### End Code Here

    def pop(self):
        ### Your Code Here
        if self.__stack:
          return self.__stack.pop()
        else:
          raise IndexError("pop from an empty custom stack")
        ### End Code Here

    def push(self, value):
        ### Your Code Here
        if self.is_full():
          raise OverflowError("push to a full stack")
        else:
          self.__stack.append(value)
        ### End Code Here

    def top(self):
        ### Your Code Here
        if self.__stack:
          # return self.__stack[len(self.__stack) - 1]
          return self.__stack[-1]
        else:
          # print("stack is empty")
          # return None
          raise IndexError("top from empty stack")
        ### End Code Here

In [ ]:
stack1 = MyStack(capacity=5)

stack1.push(1)

stack1.push(2)

print(stack1.is_full())

print(stack1.top())

print(stack1.pop())

print(stack1.top())

print(stack1.pop())

print(stack1.is_empty())

False
2
2
1
1
True


In [ ]:
stack2 = MyStack(capacity=2)

stack2.push(1)

stack2.push(2)

print(stack2.top())

print(stack2.is_full())

print(stack2.pop())

print(stack2.pop())

print(stack2.is_empty())

print(stack2.pop())

2
True
2
1
True


IndexError: pop from an empty custom stack

## **Exercise 10**

In [75]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        ### Your Code Here
        return not self.__queue
        ### End Code Here

    def is_full(self):
        ### Your Code Here
        return len(self.__queue) == self.__capacity
        ### End Code Here

    def dequeue(self):
        ### Your Code Here
        if self.__queue:
          return self.__queue.pop(0)
        else:
          return IndexError("Queue is empty")
        ### End Code Here

    def enqueue(self, value):
        ### Your Code Here
        if self.is_full():
          return OverflowError("Enqueue to a full queue")
        else:
          self.__queue.append(value)
        ### End Code Here

    def front(self):
        ### Your Code Here
        if self.__queue:
          return self.__queue[0]
        else:
          raise IndexError("Front from empty stack")
          # print("Front from empty stack")
          # return None
        ### End Code Here

In [76]:
queue1 = MyQueue(capacity=5)

queue1.enqueue(1)

queue1.enqueue(2)

print(queue1.is_full())

print(queue1.front())

print(queue1.dequeue())

print(queue1.front())

print(queue1.dequeue())

print(queue1.is_empty())

False
1
1
2
2
True


In [77]:
queue2 =  MyQueue(capacity=2)

queue2.enqueue(1)

queue2.enqueue(2)

print(queue2.front())

print(queue2.is_full())

print(queue2.dequeue())

print(queue2.dequeue())

print(queue2.is_empty())

1
True
1
2
True


In [ ]:
queue1 = MyQueue(capacity=2)

queue1.enqueue(1)

queue1.enqueue(2)

queue1.enqueue(2)

OverflowError('Enqueue to a full queue')

Multichoices questions

In [ ]:
#1
import torch

#input data
x = torch.tensor([5.0, 3.0])

# sigmoid function
output = torch.sigmoid(x)
print(output)

tensor([0.9933, 0.9526])


In [ ]:
data = torch.Tensor([3.0, -2.0])
my_sigmoid = MySigmoid()
output = my_sigmoid(data)
output

tensor([0.9526, 0.1192])

# Multi choices questions