<a href="https://colab.research.google.com/github/mylethidiem/zero-to-hero/blob/main/preAIO25/warmup/lesson_w5/code_monday/image_data_monday.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basic**

## **Numpy array creation**

In [3]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

arr = np.zeros(4)
print(arr)

arr = np.arange(start=1, stop=4, step=2)
print(arr)

arr = np.random.rand(2)
print(arr)

arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.18537775 0.03859664]
[4.9e-324 9.9e-324 1.5e-323]


In [5]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full(shape=(2,4), fill_value=2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [11]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr[0])
arr[1] = 3
print(arr)

print(arr[-4])
print(arr)

arr[-3] = 2.0
print(arr)

print("###")
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])
print(arr[0][3])
print(arr[-2][3])

arr[1] = 3.0
print(arr)
arr[0][-3] = 3.0
print(arr)
print("###")
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr[0], end='\n')
print(arr[0][0::2], end='\n')#Lấy hàng đầu, chọn cột 0, 2

print(arr[0:2, 1:3])#Lấy hàng 0,1 và cột 1,2
print(arr[0:2, -4::2])#Lấy hàng 0,1 và cột 0,2

1.0
[1. 3. 3. 4.]
1.0
[1. 3. 3. 4.]
[1. 2. 3. 4.]
###
4.0
4.0
[[1. 2. 3. 4.]
 [3. 3. 3. 3.]]
[[1. 3. 3. 4.]
 [3. 3. 3. 3.]]
###
[1. 2. 3. 4.]
[1. 3.]
[[2. 3.]
 [6. 7.]]
[[1. 3.]
 [5. 7.]]


In [10]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])
print(np.where(arr%2 == 0, 'even', 'odd'))
print(np.where(arr<5, arr, arr + 10))
print(np.where(arr>5, arr, -1))

[['odd' 'even' 'odd' 'even']
 ['odd' 'even' 'odd' 'even']]
[[ 1.  2.  3.  4.]
 [15. 16. 17. 18.]]
[[-1. -1. -1. -1.]
 [-1.  6.  7.  8.]]


## **Vector Operations**

## **Matrix Operations**

## **Read and show an image**

###**Using matplotlib**

###**Using matplotlib and opencv**

True

0

255

##**Read and Write an image**

True

###**Using list as intermediate data**

Height: 500 and width:1200


True

##**Create black and noise images**

True

True

#**Simple Applications**

##**Copy an image**

True

True

**For Color Image**

True

##**Change illuminations**

True

True

#**Background Subtraction**

In [ ]:

resized_matrix

array([[4, 5, 7, 8],
       [4, 4, 6, 7],
       [3, 3, 4, 5],
       [2, 2, 3, 4]], dtype=uint8)

True

array([[ 0,  0,  0,  0],
       [ 0, 20, 11,  0],
       [ 0,  0,  0,  0]], dtype=uint8)

array([[ 0,  0,  0,  0],
       [ 0, 20, 11,  0],
       [ 0,  0,  0,  0]], dtype=uint8)

array([[  0,   0,   0,   0],
       [  0, 255,   0,   0],
       [  0,   0,   0,   0]], dtype=uint8)

True

True