<a href="https://colab.research.google.com/github/mylethidiem/ProgramingTech/blob/main/preAIO25/warmup/exercise_w7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **W7**

## **Linear Regression**

#### Exercise 1

In [13]:
#q1
import numpy as np
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
arr_a = np.ones((3 ,3)) > 0
print(arr_a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [64]:
arr_b = np.ones((3 ,3), dtype = bool)
print(arr_a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [23]:
#q2
arr2 = np.full((3,3), True, dtype=bool)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
#q3
arr3 = np.arange(0,10)
print(arr3[arr3 % 2 == 1])

[1 3 5 7 9]


In [16]:
#q4
arr4 = np.arange(0,10)
arr4[arr4 % 2 == 1] = -1
print(arr4)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [25]:
#q5
arr5 = np.arange(10) # 1D
arr_2d = arr5.reshape(2,-1)
 #2D: array with 2 row,-1 mean number of column will automatically computation
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
#q6
arr5 = np.arange(10).reshape(2,-1)
print(arr5)
print(arr5.shape)
arr6 = np.repeat(1, 10).reshape(2,-1)
print(np.repeat(1, 10))
print(arr6)
print(arr6.shape)
c = np.concatenate([arr5, arr6], axis=0)
#axis = 0 mean row
print("Result of concatenation along axis 0:\n",c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[1 1 1 1 1 1 1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]]
(2, 5)
Result of concatenation along axis 0:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
#q7
arr7 = np.arange(10).reshape(2,-1)
print(arr7)
arr8 = np.repeat(1, 10).reshape(2,-1)
print(arr8)
d = np.concatenate([arr7, arr8], axis=1)
#axis = 1 mean column
print("Result of concatenation along axis 1:\n",d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
Result of concatenation along axis 1:
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [28]:
#q8
arr9 = np.array([1,2,3])
# repeat each element in array
# tile the whole array
print(np.repeat(arr9, 3))
print(np.tile(arr9, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [29]:
#q9
a = np.array([2,6,1,9,10,3,27])
index = np.where((a >= 5) & (a <= 10))
print("result of index where values are between 5 and 10:",a[index])

result of index where values are between 5 and 10: [ 6  9 10]


In [59]:
import numpy as np
#q10
def maxx(x,y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

#vectorize la ham numpy dung de vector hoa' mot ham py thong thuong
#ap dung ham maxx len tung cap phan tu tuong ung trong mang a va b
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [31]:
import numpy as np
#q11
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])
print("Result", np.where(a<b,b,a))

Result [6 7 9 8 9 7 5]


#### Exercise 2

In [34]:
# Download data!
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 8.13MB/s]


In [36]:
import pandas as pd
df = pd.read_csv('advertising.csv')
df.head()


TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [39]:
data = df.to_numpy()

In [40]:
def get_column(data, col_index):
  return data[:, col_index]

In [47]:
#q12
sales = get_column(data,3)
print(sales)
print(f"Max sale value is {np.max(sales)} at index {np.argmax(sales)}")

[22.1 10.4 12.  16.5 17.9  7.2 11.8 13.2  4.8 15.6 12.6 17.4  9.2 13.7
 19.  22.4 12.5 24.4 11.3 14.6 18.  17.5  5.6 20.5  9.7 17.  15.  20.9
 18.9 10.5 21.4 11.9 13.2 17.4 11.9 17.8 25.4 14.7 10.1 21.5 16.6 17.1
 20.7 17.9  8.5 16.1 10.6 23.2 19.8  9.7 16.4 10.7 22.6 21.2 20.2 23.7
  5.5 13.2 23.8 18.4  8.1 24.2 20.7 14.  16.  11.3 11.  13.4 18.9 22.3
 18.3 12.4  8.8 11.  17.   8.7  6.9 14.2  5.3 11.  11.8 17.3 11.3 13.6
 21.7 20.2 12.  16.  12.9 16.7 14.   7.3 19.4 22.2 11.5 16.9 16.7 20.5
 25.4 17.2 16.7 23.8 19.8 19.7 20.7 15.   7.2 12.   5.3 19.8 18.4 21.8
 17.1 20.9 14.6 12.6 12.2  9.4 15.9  6.6 15.5  7.  16.6 15.2 19.7 10.6
  6.6 11.9 24.7  9.7  1.6 17.7  5.7 19.6 10.8 11.6  9.5 20.8  9.6 20.7
 10.9 19.2 20.1 10.4 12.3 10.3 18.2 25.4 10.9 10.1 16.1 11.6 16.6 16.
 20.6  3.2 15.3 10.1  7.3 12.9 16.4 13.3 19.9 18.  11.9 16.9  8.  17.2
 17.1 20.   8.4 17.5  7.6 16.7 16.5 27.  20.2 16.7 16.8 17.6 15.5 17.2
  8.7 26.2 17.6 22.6 10.3 17.3 20.9  6.7 10.8 11.9  5.9 19.6 17.3  7.6
 14.  1

In [48]:
#q13
tv = get_column(data, 0)
print(f"Average TV advertising is {np.mean(tv)}")

Average TV advertising is 147.0425


In [53]:
#q14
count = 0
for i in range(len(sales)):
  if sales[i] >= 20:
    count+=1
print(f"Number of sales >= 10 is {count}")

Number of sales >= 10 is 40


In [50]:
#q15
radio = get_column(data, 1)
sum_radio = 0
count = 0
for i in range(len(sales)):
  if sales[i] >= 15:
    sum_radio+=radio[i]
    count+=1
print(f"Average radio advertising when sales >= 15 is {sum_radio/count}")

Average radio advertising when sales >= 15 is 26.222935779816517


In [55]:
#q16
newspaper = get_column(data,2)
sum_sales = 0
average_newspaper = np.mean(newspaper)
for i in range(len(newspaper)):
  if newspaper[i] > average_newspaper:
    sum_sales += sales[i]

print(f"Sum of sales where value of newspaper larger than value of average of newspaper colum is {sum_sales}")

Sum of sales where value of newspaper larger than value of average of newspaper colum is 1405.1000000000004


In [58]:
#q17
sales_average = np.mean(sales)
print(f"Average of sales is {sales_average}")
#intialize empty np array scores
scores = np.array([])
for i in range(len(sales)):
  if sales[i] > sales_average:
    scores = np.append(scores, 'Good')
  elif sales[i] == sales_average:
    sscores = np.append(scores, 'Average')
  else:
    scores = np.append(scores, 'Bad')

print(scores)
print(f"Value sales [7:10]: {scores[7:10]}")

Average of sales is 15.130500000000001
['Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad'
 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good'
 'Bad' 'Good' 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Bad'
 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Good' 'Good' 'Good'
 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Good'
 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad'
 'Bad' 'Bad' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad'
 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good'
 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Good' 'Good' 'Good'
 'Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good'
 'Good' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Good'
 'Bad' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad' 'Good'
 'Bad' 'Good' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Good' 'Bad' 'Good' 'Good'
 'Bad' 'Bad' 'Ba

In [62]:
#q18
#find the value nearest to the average value of sales column

sales_average = np.mean(sales)
print(f"Average of sales is {sales_average}")
#np.argmin: Trả về chỉ số (index) của phần tử nhỏ nhất trong mảng
nearest_average_sales = sales[np.argmin(np.abs(sales - sales_average))]
print(f"The value nearest to the average value of sales column is {nearest_average_sales}")

#intialize empty np array scores
scores = np.array([])
# create scores array
for i in range(len(sales)):
  if sales[i] > nearest_average_sales:
    scores = np.append(scores, 'Good')
  elif sales[i] == nearest_average_sales:
    sscores = np.append(scores, 'Average')
  else:
    scores = np.append(scores, 'Bad')

print(scores)
print(f"Value sales [7:10]: {scores[7:10]}")

Average of sales is 15.130500000000001
The value nearest to the average value of sales column is 15.2
['Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad'
 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good'
 'Bad' 'Good' 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Bad'
 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Good' 'Good' 'Good'
 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad' 'Good' 'Good' 'Good'
 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Bad'
 'Bad' 'Bad' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad'
 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good'
 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Good' 'Bad' 'Good' 'Good' 'Good' 'Good'
 'Good' 'Good' 'Good' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good'
 'Good' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Good'
 'Bad' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Good' 'Bad' 'Bad' 'Good' 'Bad'
 'Good' 'Bad' 'Bad' 'Bad' 