### Phép toán trên mảng(Array Math)

In [3]:
import numpy as np

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x :', x)
print('data y :', y)

# Tổng của 2 mảng
print('sum method 1: ', x + y)
print('sum method 2: ', np.add(x, y))

print('substract method 1: ', x - y)
print('substract method 2: ', np.subtract(x, y))

print('multiply method 1: ', x*y)
print('multiply method 2: ', np.multiply(x, y))

print('divide method 1 : ', x / y)
print('divide method 2 : ', x // y)
print('divide method 3 : ', np.divide(x, y))

data x : [1 2 3 4]
data y : [5 6 7 8]
sum method 1:  [ 6  8 10 12]
sum method 2:  [ 6  8 10 12]
substract method 1:  [-4 -4 -4 -4]
substract method 2:  [-4 -4 -4 -4]
multiply method 1:  [ 5 12 21 32]
multiply method 2:  [ 5 12 21 32]
divide method 1 :  [0.2        0.33333333 0.42857143 0.5       ]
divide method 2 :  [0 0 0 0]
divide method 3 :  [0.2        0.33333333 0.42857143 0.5       ]


In [5]:
data = np.array([1,2,3,4])

print('data: ', data)

# Căn bậc 2 từng phần tử trong data
print('sqrt : ', np.sqrt(data))

data:  [1 2 3 4]
sqrt :  [1.         1.41421356 1.73205081 2.        ]


In [10]:
v = np.array([1, 2])
w = np.array([2, 3])

# Tính inner product giữa v và w
print('method 1:', v.T.dot(w))
print('method 1.1:', v.dot(w))
print('method 2:', np.dot(v, w))

method 1: 8
method 1.1: 8
method 2: 8


In [9]:
X = np.array([[1,2],[4,3]])
v = np.array([1,2])

print('matrix X:\n ', X)
print('vector v:\n ', v)

# phép nhân giữa ma trận và vector
print('method 1: X.dot(v):', X.dot(v))
print('method 1: v.dot(X):', v.dot(X))
print('method 2: X.dot(v):', np.dot(X, v))
print('method 2: v.dot(X):', np.dot(v, X))

matrix X:
  [[1 2]
 [4 3]]
vector v:
  [1 2]
method 1: X.dot(v): [ 5 10]
method 1: v.dot(X): [9 8]
method 2: X.dot(v): [ 5 10]
method 2: v.dot(X): [9 8]


In [11]:
X = np.array([[1,2],[4,3]])
Y = np.array([[2,3],[2,1]])

print(' matrix X \n', X)
print('\n matrix Y \n', Y)

# Phép nhân giữa hai ma trận
print('\n method 1 \n', X.dot(Y))
print('\n method 2 \n', np.dot(X, Y))

 matrix X 
 [[1 2]
 [4 3]]

 matrix Y 
 [[2 3]
 [2 1]]

 method 1 
 [[ 6  5]
 [14 15]]

 method 2 
 [[ 6  5]
 [14 15]]


### sum

In [ ]:
X = np.array([[1,2],
              [3,4]])

# Tổng các phần tử của mảng
print(np.sum(X))

 # Tính tổng theo từng cột
print(np.sum(X, axis=0))

# Tính tổng theo từng dòng
print(np.sum(X, axis=1))


10
[4 6]
[3 7]


In [ ]:
X = np.array([[1,2],
              [3,4]])
print(X)

#chuyển vị
print(X.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### argmin and argmax

In [14]:
import numpy as np
x = np.array([4, 7, 1, 5])
result_argmin = np.argmin(x)
x = np.array([4, 7, 1, 5])
result_argmax= np.argmax(x)
print(result_argmin)
print(result_argmax)

2
1


### min and max

30


### sum and average

In [17]:
import numpy as np

x = np.array([6, 5, 7, 1, 9, 2])
result = np.mean(x)
print(result)

5.0


In [16]:
x = np.array([6, 5, 7, 1, 9, 2])
result = np.sum(x)
print(result)

30
